# Site Build Settings

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
url:                 https://normanjseeger.com
plugins:             [jekyll-sitemap, jekyll-seo-tag]
# plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]


# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Norman J. Seeger'
description:	       'Research & Data'
author:              'Norman J. Seeger'
