# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Home',   url: 'index.html'}
- {name: 'CV',   url: 'cv.html'}
- {name: 'Publications', url: 'publications.html'}
- {name: 'Contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'github',     link: 'https://www.github.com/lenpaul'}
- {icon: 'twitter',    link: 'https://twitter.com/normanseeger'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/norman-seeger-3b701a7/'}
# - {icon: 'envelope',   link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}
